### ISSUE TITLE
No results found on database list for new install

### ISSUE THREAD

**Issue by rgormley** [square/shift#29]
I'm a Rails noob:

Configured database.yml - added a development database.

Running db:setup created the database (though did not populate cluster).

Added a cluster, per the insert statement.

Edited config/environments/development.rb to point to the DB server.

But creating a New Migration Request "fails". I can see the cluster, but looking at databases shows "No results found"

**Comment by michaelfinch** [comment]
Hey, it sounds like the rails app does not have the access to read the databases on your cluster. Can you make sure that the credentials you entered in development.rb (here: https://github.com/square/shift/blob/master/ui/config/environments/development.rb#L54) have access to read from the `rw_host` of your cluster?

**Comment by rgormley** [comment]
Looks good to me:

https://gist.github.com/rgormley/4bcf7eb5cdc8721214ed41bb30a0cc88

**Comment by michaelfinch** [comment]
Your setup looks good for the most part. You should remove the host field from `config.x.mysql_helper.db_config` since you just need credentials here - the host will end up being whatever the `rw_host` is of the cluster you select.

I've added some more logging, so if you pull master you should see something like this in the logs if it's still not working
```
#<MysqlError: Problem establishing mysql connection (error: Access denied for user 'john'@'localhost' (using password: YES)) (connection info: {:username=>"john", :password=>"*****", :host=>"localhost", :connect_timeout=>5})>
```

Also, in case you don't already know, you need to restart the rails server when you update anything in the config directory.

**Comment by rgormley** [comment]
Okay, progress made.

Removed host from `config.x.mysql_helper.db_config`. 

RW Host is definitely the DB servers IP address (not local), but still:

```
#<MysqlError: Problem establishing mysql connection (error: Access denied for user 'shift'@'localhost' (using password: YES)) (connection info: {:username=>"shift", :password=>"*****", :host=>"localhost", :connect_timeout=>5})>
```

when I look at the database list. It's reading the cluster list correctly from the DB (I renamed the cluster and it reflected that change).

And with some hunting I see the issue: `ui/app/services/mysql_helper.rb` is hardcoded to 'localhost' for dev and test.

I took the liberty of creating a PR for this, feel free to accept or reject as to how it reflects methodology: https://github.com/square/shift/pull/35

**Comment by michaelfinch** [comment]
oh duh, sorry, I should have noticed that. I'll go ahead and merge your PR

**Comment by rgormley** [comment]
Awesome, appreciate the help - migrations are running smoothly.
