### ISSUE TITLE
Question: did you ever consider migrating to a different data store?

### ISSUE THREAD

**Issue by jondot** [square/shift#3]
Such as Postgres, that provides O(1) migrations, rather than develop a system and use online-schema-change that anyways copies the entire table to do modifications (so is still slow, right?).
If you're doing this 100 times a day I can't shake the feeling that this is a lot of new tables and data shuffling that increase risk and churn on database servers.
Am I missing something?

Thanks!

**Comment by slyglif** [comment]
We actually did start switching to Postgres several years ago but aborted the attempt about six months after starting for a few of reasons.

The first was a lack of a good method of doing major version upgrades without downtime (Postgres requires masters be upgraded before slaves, and the alternate replication methods such as Slony weren't considered reliable enough).

Second was the storage format hasn't been as reliable for Postgres when compared to InnoDB.  Every third or fourth point release had a corruption bug that required doing full index rebuilds after the next upgrade, during which time the index is locked for at least writes, and sometimes reads as well.

Third was we have hundreds of applications, each with their own database.  Migrating each of those applications would be a major undertaking with minimal payback.  Even migrating the few applications we had on Postgres to MySQL (for consistency of tooling) has been an undertaking.

**Comment by jondot** [comment]
Thanks!
