### ISSUE TITLE
Question: Would this work with AWS RDS?

### ISSUE THREAD

**Issue by gordonmurray** [square/shift#32]
Would this work on mySQL (or MariaDB) database's hosted on AWS RDS?

**Comment by michaelfinch** [comment]
Yes I believe so. I haven't run shift on either of those specifically, but as long as pt-osc works shift should be fine.

**Comment by gordonmurray** [comment]
Great, I'll try it out on a VM in the coming days and report back, in case others are curious in the future

**Comment by michaelfinch** [comment]
Awesome, let me know how it goes

**Comment by konrness** [comment]
@gordonmurray any luck?

**Comment by khurramnaseem** [comment]
I'm testing this with RDS but still not sure which file I should edit to list DB instances and what is the purpose and use of cluster drop down.
