### ISSUE TITLE
[GOLANG] Runner switch to vendoring

### ISSUE THREAD

**Issue by panzerdev** [square/shift#41]
Is there a reason why the workspace approach was choosen and not the vendoring one?

Would you be interested in a PR changing that based on Godep?

**Comment by michaelfinch** [comment]
I think I started this project before the vendor experiment started, but yeah, I would like to switch to it. PR definitely welcome

**Comment by panzerdev** [comment]
Alright! I'll give it a try with the vendoring and see if it works out as easy I think it'll be.
