### ISSUE TITLE
Shift creating shadow table

### ISSUE THREAD

**Issue by Dhanasekar93** [square/shift#52]
After completion of migration, the shift is creating a shadow table like below 

```mysql> show tables;
+---------------------------+
| Tables_in_test            |
+---------------------------+
| 20181004125700887_sbtest1 |
| 20181004130253090_sbtest5 |
| 20181004130952087_sbtest5 |
| 20181005112052953_sbtest5 |
| 20181005112924812_sbtest5 |
| 20181005112924891_sbtest5 |
| 20181005112924892_sbtest5 |
| 20181005113204700_sbtest5 |
| 20181005113431865_sbtest5 |
| 20181005121503073_sbtest5 |
| sbtest1                   |
| sbtest2                   |
| sbtest3                   |
| sbtest4                   |
| sbtest5                   |
+---------------------------+```

Do we have any parameters to stop this ?

**Comment by michaelfinch** [comment]
Currently, no, although I think this was an oversight because we definitely should.

**Comment by Dhanasekar93** [comment]
This will be an overhead for big tables. We can skip the rename migration part and make it to drop the old table. 

Also wanted to know, do we have any scheduled migration kind of process ?

**Comment by michaelfinch** [comment]
Just to provide some background on why it is the way it is - we define the "pending_drops_db" configuration option on the runner to be a special db, and we have a cron job that drops tables that are older than 7 days from that db. I agree, though, that we should provide a way to just drop the table immediately after the migration finishes.

You cannot schedule things to run at a specific time in the future, if that's what you're asking.

**Comment by cadl** [comment]
@Dhanasekar93 @michaelfinch How about adding a parameter like `enable_trash`? I would like to create PR about it.

**Comment by michaelfinch** [comment]
That sounds good, I'll definitely accept that PR. Please update the docs as well

**Comment by michaelfinch** [comment]
Alternatively, if `pending_drops_db` is empty in the config, we could just make it automatically drop the old table.

**Comment by cadl** [comment]
@michaelfinch I have created a pull request about it~  #55

**Comment by Dhanasekar93** [comment]
If enable_trash is false it is dropping the shadow table

**Comment by michaelfinch** [comment]
Isn't that the behavior we want? From the README: `enable_trash`: boolean. if true, the runner move the original table into the `pending_drops_db` with a timestamp prefix name after non-shortrun alter/drop table.

So if enable_trash is false, it should drop the shadow table. If it is true, it should move the shadow table into the pending_drops db.
