### ISSUE TITLE
Can't locate YAML/Syck.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/bin/pt-online-schema-change line 3644.

### ISSUE THREAD

**Issue by raghavendrablu** [square/shift#53]
when i try to start the migartion its failing with 
Can't locate YAML/Syck.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/bin/pt-online-schema-change line 3644.

**Comment by michaelfinch** [comment]
Can you `yum install perl-YAML-Syck`, or whatever the equivalent on your OS distribution is?

**Comment by raghavendrablu** [comment]
it resolved it
