### ISSUE TITLE
Data is missing because of rename migration

### ISSUE THREAD

**Issue by Dhanasekar93** [square/shift#56]
Data is missing if the rename migration takes time inbetween.

Below is the screenshot of the migration:
![screenshot 2018-12-28 at 12 50 40 pm](https://user-images.githubusercontent.com/26372199/50506575-a670d100-0a9f-11e9-9d6d-405a3f30dc7a.png)

Before starting migration row count - 986,408
After completing migration row count - 986,473

**Comment by michaelfinch** [comment]
Rows aren't actually missing. That count comes from the `rows` column in information_schema.tables. The docs for that column say "For InnoDB tables, the row count is only a rough estimate used in SQL optimization." (https://dev.mysql.com/doc/refman/5.6/en/tables-table.html)

I've added an FAQ entry for this: https://github.com/square/shift/wiki/Frequently-Asked-Questions
